# Generated by Django 5.1.1 on 2024-10-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seggtech', '0002_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
